import { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'N3xus',
  description: 'Generated by create-solana-dapp',
  viewport: 'width=device-width, initial-scale=1',
  icons: {
    icon: '/favicon.ico',
  },
}
